# Pre-define Devices
[[DeviceList]]
  Name = "Uart-Generic-Device"
  ProfileName = "Uart-Generic-Device"
  Description = "Example of Device UART"
  Labels = [ "device-uart-example" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "device-uart-generic-01"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Interval = '2s'
    OnChange = false
    SourceName = 'Read_Cmd'
